### ISSUE TITLE
TinyMCE conflict on WordPress 4.7.5

### ISSUE THREAD

**Issue by danaskallman** [relldoesphp/com.aghstrategies.tinymce#6]
When this extension is enabled and the CiviCRM shortcode adding button above the visual editor is on the content type, the visual editor in WordPress, cannot be used. There's a lot updates currently going into [TinyMCE for WordPress](https://github.com/WordPress/gutenberg/) that are going to be into core. So am wondering if it's version conflicts. 

* Is there a way to use the same version of TinyMCE if the CMS has it and if not use what's in the extension? 
* Or maybe not load it on the WP side at all when the CiviCRM shortcode button is enabled on that content type?
* Or something else...?

![tinymce-conflict](https://cloud.githubusercontent.com/assets/1139085/26650498/97508ed4-4617-11e7-96ae-6820d297ba06.png)

**Comment by themak1985** [comment]
I am not getting those errors in wordpress, but the TinyMCE plugin is non-existent in CiviCRM with WP 4.7.5 and CiviCRM 4.7.19 - reverted to CKeditor for now.
