### ISSUE TITLE
Toolbar isn't appearing

### ISSUE THREAD

**Issue by Shynath** [relldoesphp/com.aghstrategies.tinymce#8]
Hello,

when switching to "Tiny MCE" in CiviCRM 4.7.31,the toolbar is not visible. How can i fix this?

Thanks in advance

**Comment by colemanw** [comment]
Hi, could you please give details like

-Your CMS
- What other extensions are you using e.g. Shoreditch
- A screenshot would be helpful, I'm not sure precisely what you mean by "toolbar"

**Comment by Shynath** [comment]
Hello,
the CMS is Joomla! 3.8.6 , i don't use Shoreditch. It turned out that when you select "Tiny MCE" as  WYSIWYG Editor, the Textarea is shown instead, thats why no toolbar is visible ;) .
These extensions are activated:

Show Contact Deceased(biz.jmaconsulting.showcontactdeceased) | Aktiviert | 1.0 | Module | Deaktivieren

CiviCRM Log Viewer(ca.civicrm.logviewer) | Aktiviert | 1.1 | Module | Deaktivieren
TinyMCE(com.aghstrategies.tinymce) | Aktiviert | 1.4 | Module | Deaktivieren
iATS Payments(com.iatspayments.civicrm) |   | 1.6.1 | Module | Installieren
Save time preparing newsletters: Fancy tokens for upcoming events, contribution pages, and forms(com.pogstone.fancytokens) | Aktiviert | 4.0 | Module | Deaktivieren
Bootstrap layout for civisualize(eu.tttp.bootstrapvisualize) | Aktiviert | 1.0 | Module | Deaktivieren
Export to Excel(eu.tttp.exportexcel) | Aktiviert | 1.2 | Module | Deaktivieren
Summary Fields(net.ourpowerbase.sumfields) | Aktiviert | 3.1.3 | Module | Deaktivieren
Spendenbescheinigungen (German donation receipts)(sfe.donationreceipts)

Kind Regards

**Comment by Shynath** [comment]
I solved the problem by cleaning the caches and updating the paths :)
